# Generated by Django 4.1.1 on 2022-10-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_text', models.CharField(max_length=200)),
                ('kvm_price_start', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kvm_price_end', models.DecimalField(decimal_places=2, max_digits=10)),
                ('association_kvm_loan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('view_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
