# Generated by Django 4.1.1 on 2022-10-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lghter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='owns_land',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='renovation_rating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='storehouse_rating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='two_bath_rating',
            field=models.BooleanField(default=False),
        ),
    ]
