# Generated by Django 4.1.1 on 2022-10-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lghter', '0004_rename_renovation_rating_apartment_renovation_need_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='balcony_rating',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
